/**
 * Comprehensive IATA airline database for admin markup configuration.
 * Sorted alphabetically by name. Covers 200+ major airlines worldwide.
 */
export interface AirlineEntry {
  code: string;
  name: string;
  country: string;
  alliance?: string;
}

export const AIRLINES_DATABASE: AirlineEntry[] = [
  { code: "9W", name: "Jet Airways", country: "India" },
  { code: "AA", name: "American Airlines", country: "USA", alliance: "oneworld" },
  { code: "AB", name: "Air Berlin", country: "Germany" },
  { code: "AC", name: "Air Canada", country: "Canada", alliance: "Star Alliance" },
  { code: "AD", name: "Azul Brazilian Airlines", country: "Brazil" },
  { code: "AF", name: "Air France", country: "France", alliance: "SkyTeam" },
  { code: "AH", name: "Air Algérie", country: "Algeria" },
  { code: "AI", name: "Air India", country: "India", alliance: "Star Alliance" },
  { code: "AK", name: "AirAsia", country: "Malaysia" },
  { code: "AM", name: "Aeroméxico", country: "Mexico", alliance: "SkyTeam" },
  { code: "AR", name: "Aerolíneas Argentinas", country: "Argentina", alliance: "SkyTeam" },
  { code: "AS", name: "Alaska Airlines", country: "USA", alliance: "oneworld" },
  { code: "AT", name: "Royal Air Maroc", country: "Morocco", alliance: "oneworld" },
  { code: "AV", name: "Avianca", country: "Colombia", alliance: "Star Alliance" },
  { code: "AY", name: "Finnair", country: "Finland", alliance: "oneworld" },
  { code: "AZ", name: "ITA Airways", country: "Italy", alliance: "SkyTeam" },
  { code: "B6", name: "JetBlue Airways", country: "USA" },
  { code: "BA", name: "British Airways", country: "UK", alliance: "oneworld" },
  { code: "BD", name: "Biman Bangladesh Airlines", country: "Bangladesh" },
  { code: "BG", name: "Biman Bangladesh Airlines", country: "Bangladesh" },
  { code: "BI", name: "Royal Brunei Airlines", country: "Brunei" },
  { code: "BJ", name: "Nouvelair", country: "Tunisia" },
  { code: "BR", name: "EVA Air", country: "Taiwan", alliance: "Star Alliance" },
  { code: "BS", name: "US-Bangla Airlines", country: "Bangladesh" },
  { code: "BT", name: "airBaltic", country: "Latvia" },
  { code: "BW", name: "Caribbean Airlines", country: "Trinidad & Tobago" },
  { code: "CA", name: "Air China", country: "China", alliance: "Star Alliance" },
  { code: "CI", name: "China Airlines", country: "Taiwan", alliance: "SkyTeam" },
  { code: "CM", name: "Copa Airlines", country: "Panama", alliance: "Star Alliance" },
  { code: "CX", name: "Cathay Pacific", country: "Hong Kong", alliance: "oneworld" },
  { code: "CZ", name: "China Southern Airlines", country: "China", alliance: "SkyTeam" },
  { code: "D7", name: "AirAsia X", country: "Malaysia" },
  { code: "DE", name: "Condor", country: "Germany" },
  { code: "DL", name: "Delta Air Lines", country: "USA", alliance: "SkyTeam" },
  { code: "DV", name: "SCAT Airlines", country: "Kazakhstan" },
  { code: "E5", name: "Air Arabia Egypt", country: "Egypt" },
  { code: "EI", name: "Aer Lingus", country: "Ireland" },
  { code: "EK", name: "Emirates", country: "UAE" },
  { code: "EN", name: "Air Dolomiti", country: "Italy", alliance: "Star Alliance" },
  { code: "ET", name: "Ethiopian Airlines", country: "Ethiopia", alliance: "Star Alliance" },
  { code: "EW", name: "Eurowings", country: "Germany" },
  { code: "EY", name: "Etihad Airways", country: "UAE" },
  { code: "F9", name: "Frontier Airlines", country: "USA" },
  { code: "FD", name: "Thai AirAsia", country: "Thailand" },
  { code: "FJ", name: "Fiji Airways", country: "Fiji", alliance: "oneworld" },
  { code: "FR", name: "Ryanair", country: "Ireland" },
  { code: "FZ", name: "flydubai", country: "UAE" },
  { code: "G3", name: "GOL Linhas Aéreas", country: "Brazil" },
  { code: "G8", name: "Go First", country: "India" },
  { code: "G9", name: "Air Arabia", country: "UAE" },
  { code: "GA", name: "Garuda Indonesia", country: "Indonesia", alliance: "SkyTeam" },
  { code: "GF", name: "Gulf Air", country: "Bahrain" },
  { code: "GK", name: "Jetstar Japan", country: "Japan" },
  { code: "H1", name: "Hahn Air", country: "Germany" },
  { code: "HA", name: "Hawaiian Airlines", country: "USA" },
  { code: "HG", name: "NIKI", country: "Austria" },
  { code: "HM", name: "Air Seychelles", country: "Seychelles" },
  { code: "HU", name: "Hainan Airlines", country: "China" },
  { code: "HX", name: "Hong Kong Airlines", country: "Hong Kong" },
  { code: "HY", name: "Uzbekistan Airways", country: "Uzbekistan" },
  { code: "IB", name: "Iberia", country: "Spain", alliance: "oneworld" },
  { code: "IG", name: "Air Italy", country: "Italy" },
  { code: "IR", name: "Iran Air", country: "Iran" },
  { code: "IX", name: "Air India Express", country: "India" },
  { code: "J2", name: "Azerbaijan Airlines", country: "Azerbaijan" },
  { code: "J9", name: "Jazeera Airways", country: "Kuwait" },
  { code: "JL", name: "Japan Airlines", country: "Japan", alliance: "oneworld" },
  { code: "JQ", name: "Jetstar Airways", country: "Australia" },
  { code: "K6", name: "Cambodia Angkor Air", country: "Cambodia" },
  { code: "KC", name: "Air Astana", country: "Kazakhstan" },
  { code: "KE", name: "Korean Air", country: "South Korea", alliance: "SkyTeam" },
  { code: "KL", name: "KLM Royal Dutch Airlines", country: "Netherlands", alliance: "SkyTeam" },
  { code: "KM", name: "Air Malta", country: "Malta" },
  { code: "KQ", name: "Kenya Airways", country: "Kenya", alliance: "SkyTeam" },
  { code: "KU", name: "Kuwait Airways", country: "Kuwait" },
  { code: "LA", name: "LATAM Airlines", country: "Chile" },
  { code: "LH", name: "Lufthansa", country: "Germany", alliance: "Star Alliance" },
  { code: "LI", name: "LIAT", country: "Antigua" },
  { code: "LO", name: "LOT Polish Airlines", country: "Poland", alliance: "Star Alliance" },
  { code: "LX", name: "Swiss International Air Lines", country: "Switzerland", alliance: "Star Alliance" },
  { code: "LY", name: "El Al", country: "Israel" },
  { code: "ME", name: "Middle East Airlines", country: "Lebanon", alliance: "SkyTeam" },
  { code: "MF", name: "Xiamen Airlines", country: "China", alliance: "SkyTeam" },
  { code: "MH", name: "Malaysia Airlines", country: "Malaysia", alliance: "oneworld" },
  { code: "MI", name: "SilkAir", country: "Singapore" },
  { code: "MK", name: "Air Mauritius", country: "Mauritius" },
  { code: "MS", name: "EgyptAir", country: "Egypt", alliance: "Star Alliance" },
  { code: "MU", name: "China Eastern Airlines", country: "China", alliance: "SkyTeam" },
  { code: "NH", name: "All Nippon Airways (ANA)", country: "Japan", alliance: "Star Alliance" },
  { code: "NK", name: "Spirit Airlines", country: "USA" },
  { code: "NZ", name: "Air New Zealand", country: "New Zealand", alliance: "Star Alliance" },
  { code: "OA", name: "Olympic Air", country: "Greece" },
  { code: "OK", name: "Czech Airlines", country: "Czech Republic", alliance: "SkyTeam" },
  { code: "OM", name: "MIAT Mongolian Airlines", country: "Mongolia" },
  { code: "OS", name: "Austrian Airlines", country: "Austria", alliance: "Star Alliance" },
  { code: "OU", name: "Croatia Airlines", country: "Croatia", alliance: "Star Alliance" },
  { code: "OZ", name: "Asiana Airlines", country: "South Korea", alliance: "Star Alliance" },
  { code: "PC", name: "Pegasus Airlines", country: "Turkey" },
  { code: "PG", name: "Bangkok Airways", country: "Thailand" },
  { code: "PIA", name: "Pakistan International Airlines", country: "Pakistan" },
  { code: "PK", name: "Pakistan International Airlines", country: "Pakistan" },
  { code: "PR", name: "Philippine Airlines", country: "Philippines" },
  { code: "PS", name: "Ukraine International Airlines", country: "Ukraine" },
  { code: "PX", name: "Air Niugini", country: "Papua New Guinea" },
  { code: "QF", name: "Qantas", country: "Australia", alliance: "oneworld" },
  { code: "QR", name: "Qatar Airways", country: "Qatar", alliance: "oneworld" },
  { code: "QZ", name: "Indonesia AirAsia", country: "Indonesia" },
  { code: "RJ", name: "Royal Jordanian", country: "Jordan", alliance: "oneworld" },
  { code: "RO", name: "TAROM", country: "Romania", alliance: "SkyTeam" },
  { code: "S7", name: "S7 Airlines", country: "Russia", alliance: "oneworld" },
  { code: "SA", name: "South African Airways", country: "South Africa", alliance: "Star Alliance" },
  { code: "SK", name: "Scandinavian Airlines (SAS)", country: "Sweden", alliance: "SkyTeam" },
  { code: "SL", name: "Thai Lion Air", country: "Thailand" },
  { code: "SN", name: "Brussels Airlines", country: "Belgium", alliance: "Star Alliance" },
  { code: "SQ", name: "Singapore Airlines", country: "Singapore", alliance: "Star Alliance" },
  { code: "SU", name: "Aeroflot", country: "Russia", alliance: "SkyTeam" },
  { code: "SV", name: "Saudia", country: "Saudi Arabia", alliance: "SkyTeam" },
  { code: "SW", name: "Air Namibia", country: "Namibia" },
  { code: "TG", name: "Thai Airways", country: "Thailand", alliance: "Star Alliance" },
  { code: "TK", name: "Turkish Airlines", country: "Turkey", alliance: "Star Alliance" },
  { code: "TL", name: "Airnorth", country: "Australia" },
  { code: "TN", name: "Air Tahiti Nui", country: "French Polynesia" },
  { code: "TP", name: "TAP Air Portugal", country: "Portugal", alliance: "Star Alliance" },
  { code: "TR", name: "Scoot", country: "Singapore" },
  { code: "TW", name: "T'way Air", country: "South Korea" },
  { code: "U2", name: "easyJet", country: "UK" },
  { code: "UA", name: "United Airlines", country: "USA", alliance: "Star Alliance" },
  { code: "UL", name: "SriLankan Airlines", country: "Sri Lanka", alliance: "oneworld" },
  { code: "UM", name: "Air Zimbabwe", country: "Zimbabwe" },
  { code: "UP", name: "Bahamasair", country: "Bahamas" },
  { code: "UX", name: "Air Europa", country: "Spain", alliance: "SkyTeam" },
  { code: "VJ", name: "VietJet Air", country: "Vietnam" },
  { code: "VN", name: "Vietnam Airlines", country: "Vietnam", alliance: "SkyTeam" },
  { code: "VS", name: "Virgin Atlantic", country: "UK", alliance: "SkyTeam" },
  { code: "VT", name: "Air Tahiti", country: "French Polynesia" },
  { code: "VX", name: "Virgin America", country: "USA" },
  { code: "VY", name: "Vueling", country: "Spain" },
  { code: "W5", name: "Mahan Air", country: "Iran" },
  { code: "W6", name: "Wizz Air", country: "Hungary" },
  { code: "WB", name: "RwandAir", country: "Rwanda" },
  { code: "WN", name: "Southwest Airlines", country: "USA" },
  { code: "WS", name: "WestJet", country: "Canada" },
  { code: "WY", name: "Oman Air", country: "Oman" },
  { code: "XJ", name: "Thai AirAsia X", country: "Thailand" },
  { code: "XY", name: "flynas", country: "Saudi Arabia" },
  { code: "ZH", name: "Shenzhen Airlines", country: "China", alliance: "Star Alliance" },
  { code: "3K", name: "Jetstar Asia", country: "Singapore" },
  { code: "3U", name: "Sichuan Airlines", country: "China" },
  { code: "4U", name: "Germanwings", country: "Germany" },
  { code: "5J", name: "Cebu Pacific", country: "Philippines" },
  { code: "6E", name: "IndiGo", country: "India" },
  { code: "7C", name: "Jeju Air", country: "South Korea" },
  { code: "8M", name: "Myanmar Airways International", country: "Myanmar" },
].sort((a, b) => a.name.localeCompare(b.name));
